name: Build and Deploy EODHD Ingestor

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "backend/worker/**"
      - "backend/worker/ingestors/eodhd_ingestor.py"
  pull_request:
    branches: [main]
    paths:
      - "backend/worker/**"
      - "backend/worker/ingestors/eodhd_ingestor.py"

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION || 'europe-west3' }}
  SERVICE_NAME: ingestor-eodhd

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install flake8 black isort
          flake8 worker/ --max-line-length=88 --ignore=E203,W503
          black --check worker/
          isort --check-only worker/

      # Temporarily disable tests until they are implemented
      # - name: Run tests
      #   run: |
      #     pip install pytest pytest-asyncio
      #     python -m pytest worker/ -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push image
        run: |
          cd backend
          docker build -t gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --no-allow-unauthenticated \
            --set-env-vars GCP_PROJECT=$GCP_PROJECT,BQ_DATASET_RAW=quant_finance_raw,BQ_TABLE_EQ=eq_ohlcv,BQ_TABLE_CORP_ACTIONS=corporate_actions,BQ_TABLE_VENDOR_MAP=vendor_symbol_map \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10
