name: Build and Deploy Finnhub Ingestor

on:
  push:
    branches: [main]
    paths:
      - "services/ingestor_finnhub/**"
  pull_request:
    branches: [main]
    paths:
      - "services/ingestor_finnhub/**"

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION || 'us-central1' }}
  SERVICE_NAME: ingestor-finnhub

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/ingestor_finnhub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install flake8 black isort
          flake8 app/
          black --check app/
          isort --check-only app/

      - name: Run tests
        run: |
          pip install pytest pytest-asyncio
          python -m pytest tests/ -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push image
        run: |
          cd services/ingestor_finnhub
          docker build -t gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --set-env-vars GCP_PROJECT=$GCP_PROJECT,BQ_DATASET_RAW=market_raw,BQ_TABLE_RAW=eq_ohlcv \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10

      - name: Update Cloud Scheduler (if exists)
        run: |
          # Update existing scheduler job or create new one
          if gcloud scheduler jobs describe ingest-aapl-daily --project $GCP_PROJECT --location $GCP_REGION >/dev/null 2>&1; then
            SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --project $GCP_PROJECT --region $GCP_REGION --format 'value(status.url)')
            gcloud scheduler jobs update http ingest-aapl-daily \
              --project $GCP_PROJECT \
              --location $GCP_REGION \
              --uri "$SERVICE_URL/v1/ingest/finnhub/candles?symbol=AAPL&resolution=D&days=7"
          fi
