name: Build and Deploy Worker Service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "backend/worker/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/worker/**"

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION || 'europe-west3' }}
  SERVICE_NAME: quant-finance-worker

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install flake8 black isort
          flake8 worker/
          black --check worker/
          isort --check-only worker/

      # Temporarily disable tests until they are implemented
      # - name: Run tests
      #   run: |
      #     pip install pytest pytest-asyncio
      #     python -m pytest worker/ -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push image
        run: |
          cd backend/worker
          docker build -t gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$GCP_PROJECT/$SERVICE_NAME:${{ github.sha }} \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --no-allow-unauthenticated \
            --set-env-vars GCP_PROJECT=$GCP_PROJECT,BQ_DATASET_RAW=quant_finance_raw,BQ_DATASET_CURATED=quant_finance_curated,QFP_ARTIFACTS_BUCKET=${{ secrets.QFP_ARTIFACTS_BUCKET }} \
            --set-env-vars DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --memory 4Gi \
            --cpu 2 \
            --max-instances 10 \
            --timeout 900
